language: php
php:
  - 5.6
script:
    skip-cleanup: true
    keep-history: true
  - find . -type f -name *.php | xargs -n1 php -l
  - cd ${TRAVIS_BUILD_DIR}/tests;./RunVeoliaTests.sh
  - git push origin HEAD:TravisResults
# script: cd ${TRAVIS_BUILD_DIR}/tests;./RunVeoliaTestsSimple.sh
