language: php
php: 5.6
before_script:
    - find . -type f -name *.php | xargs -n1 php -l
script:
# Test veolia sud est $website=2
#  - cd ${TRAVIS_BUILD_DIR}/tests;./RunVeoliaTests.sh
  - cd ${TRAVIS_BUILD_DIR}/tests;php ./testVeoliaSudEstSimple.php 
  #- diff -B veolia_sudest_data/testVeoliaSudEst.txt veolia_sudest_data_src/testVeoliaSudEst.txt
# Test veoliaeau.fr $website=1
  - cd ${TRAVIS_BUILD_DIR}/tests;./RunVeoliaEau.sh 
  - diff -B veolia_eau_data/testVeoliaEau.txt veolia_eau_data_src/testVeoliaEau.txt
after_success:
    # TBD
    - cd ${TRAVIS_BUILD_DIR}/tests
    - ls -latr
after_failure:
    - cd ${TRAVIS_BUILD_DIR}/tests
    - cat veolia_sudest_data/testVeoliaSudEst.txt
    - grep "displayConfig" veolia_sudest_data/testVeoliaSudEst.txt > results.txt
    - grep "displayConfig" veolia_sudest_data_src/testVeoliaSudEst.txt > base.txt
    - diff  base.txt results.txt
    - ls -latr
