---
langs: [fr_FR,en_US]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation Plugin-Veolia-eau"
description: "Ceci est la documentation du plugin Veolia eau"
author: "damien916"
image: https://avatars2.githubusercontent.com/u/21956866?s=460&v=4
social:
  name: NextDom
  links:
    - https://github.com/damien916/
